apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: {{ .Release.Namespace }}
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: {{ .Values.kafka.brokers | default "kafka-broker:9092" }}
    - name: consumerGroup
      value: {{ .Values.kafka.consumerGroup | default "myapp-services" }}
    - name: authType
      value: {{ .Values.kafka.authType | default "none" }}
    {{- with .Values.kafka.sasl }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
