name: Deploy Backend to HF Spaces

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

env:
  HF_SPACE_NAME: mrowaisabdullah/ai-humanoid-robotics

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hugging Face Spaces

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Debug step to check if secret is available
      - name: Debug - Check secrets
        run: |
          echo "Checking available secrets..."
          echo "HF_TOKEN exists: ${{ secrets.HF_TOKEN != '' }}"
          if [ -z "${{ secrets.HF_TOKEN }}" ]; then
            echo "ERROR: HF_TOKEN secret is not set!"
            echo "Please add HF_TOKEN to repository secrets"
            exit 1
          fi
          echo "HF_TOKEN is set"

      - name: Setup Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Initialize HF Spaces repository
        run: |
          # Clone the empty space
          echo "Cloning HF Space..."
          git clone https://huggingface.co/spaces/${{ env.HF_SPACE_NAME }} hf-space

          # Copy backend files to space
          echo "Copying backend files..."
          cp -r backend/* hf-space/
          cp -r backend/.* hf-space/ 2>/dev/null || true

          # Create app.py for HF Spaces if it doesn't exist
          if [ ! -f hf-space/app.py ]; then
            echo "# Entry point for HF Spaces" > hf-space/app.py
            echo "import uvicorn" >> hf-space/app.py
            echo "from main import app" >> hf-space/app.py
            echo "if __name__ == '__main__':" >> hf-space/app.py
            echo "    uvicorn(app, host='0.0.0.0', port=7860)" >> hf-space/app.py
          fi

          # Ensure Dockerfile exists
          if [ ! -f hf-space/Dockerfile ]; then
            cp backend/Dockerfile hf-space/ || echo "# Dockerfile missing!" > hf-space/Dockerfile
          fi

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "Starting deployment to HF Spaces..."
          cd hf-space

          # Debug: Check if HF token is available in this step
          echo "Checking HF_TOKEN in deployment step..."
          if [ -z "$HF_TOKEN" ]; then
            echo "ERROR: HF_TOKEN not available in deployment step!"
            exit 1
          fi
          echo "HF_TOKEN is available"

          # Configure git credential helper for Hugging Face
          git config credential.helper store

          # Create credential for huggingface.co
          echo "https://hf:$HF_TOKEN@huggingface.co" > ~/.git-credentials

          # Set the remote URL with embedded token
          git remote set-url origin https://hf:$HF_TOKEN@huggingface.co/spaces/${{ env.HF_SPACE_NAME }}

          # Add all files
          git add .

          # Check if there are changes
          if git diff --staged --quiet; then
            echo "No changes to deploy"
          else
            # Commit changes
            git commit -m "Deploy backend from GitHub Actions

            🚀 Generated with [Claude Code](https://claude.com/claude-code)

            Co-Authored-By: Claude <noreply@anthropic.com>"

            # Push to Hugging Face Spaces
            echo "Pushing to Hugging Face Spaces..."
            git push origin main --force

            echo "Deployment completed successfully!"
          fi

      - name: Verify Deployment
        run: |
          echo "Backend deployed to: https://huggingface.co/spaces/${{ env.HF_SPACE_NAME }}"
          echo "API endpoint: https://${{ env.HF_SPACE_NAME }}.hf.space"

          # Wait a bit for the space to be ready
          sleep 30

          # Check if the space is responding (basic health check)
          echo "Checking deployment health..."
          curl -f "https://${{ env.HF_SPACE_NAME }}.hf.space/health" || echo "Health check failed - space might still be starting"

      - name: Notify on failure
        if: failure()
        run: |
          echo "Backend deployment failed!"
          echo "Please check the logs and verify your HF_TOKEN secret"