apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  labels:
    app: {{ .Values.name }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
